version: '3'
services:
  nextjs:
    build: .
    ports:
      - "3000:3000" # the second port is the port inside the container, the first is the port on the host, 3000:80 would expose port 80 on the host and map it to port 80 in the container
    environment:
      DATABASE_URL: "postgres://postgres:password@db:5432/twibber" # use the same details as the ones on the db service
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: twibber
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
